#Для применения русского языка этот файл нужно переименовать в config.yml
#Или используйте просто как пример.
select-tool: 289 #порох
remove-tool: 353 #сахар
chestset:
  example: #название типа
    min: 1 #минимальное количество возможного лута
    max: 3 #максимальное количество возможного лута
    customname: "Пример"
    powered: false #включить управление редстоуном
    break: false #включить разрушение сундуков
    respawn: [15, 30, 45] #время в секундах через которое стоит распаунить вещи
    items:
      - id: 268 # id предмета
        durability: -1 #если -1 то поломка будет рандомная
        random-enchant: false #включить рандомное зачарование
        enchantments:
          - name: KNOCKBACK #тип зачарования
            level: 1 #уровень зачарования
        name: "My Sword" #новое имя для вещи
        lore: ["Line 1", "Line 2", "Line 3"] #описание вещи
        amount: 1 #количество
      - id: 373
        potion-type: INSTANT_HEAL #тип зелья
        potion-level: 2 #уровень зелья
        potion-splash: false #сделать взрывным зелье
      - id: 35
        data: 14 #data вещи
        amount: 5
      - id: 397
        skull: "Notch" #ник владельца головы